Create PULL_REQUEST_TEMPLATE.md
ec-europa/ecl-twig pull request #30
Opened 2019-02-21 10:20 UTC by degliwe

2019-02-21 10:28 UTC, emeryro commented
addition proposals:
- [ ] I have added the components directly used in the template as dependencies
- [ ] my variables naming follow the guidelines (snake case for twig, camel case for javascript)
- [ ] I have provided documentation (for the "notes" tab)

2019-02-21 11:02 UTC, yhuard commented
- `camel case for javascript`: this is already checked by the linter, we don't need to add it to the checklist
- `I have put the original css as dependency`: not only the "CSS" (prefer "vanilla"), but also the "specs" package
- shall we add a bullet about the GH project or do we abandon it?

2019-02-21 11:06 UTC, yhuard commented
one more thing: 
> My component is listed in `@ecl-twig/ec-components`'s dependencies

2019-02-21 12:47 UTC, yhuard requested changes
> My component is listed in `@ecl-twig/ec-components`'s dependencies

And `pr: review needed` is only valid if the PR actually needs a review (i.e. not WIP). The rule could be more generic ("My PR has a `pr: *` label")

2019-02-21 13:07 UTC, emeryro commented
-  I have added the components directly used in the twig file (with `include`) as dependencies

Also for vanilla and specs we should say `devDependencies` instead of `dependencies` (will prevent back and forth)

2019-02-26 08:26 UTC, yhuard requested changes

2019-02-26 08:26 UTC, yhuard commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] I have added the components directly used in the twig file (with `include`) as dependencies
```suggestion
* [ ] I have added the components directly used in the twig file (with `include` or `embed`) as `dependencies`
```

2019-02-26 08:26 UTC, yhuard commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] My local `yarn.lock` was commited
```suggestion
* [ ] If my local `yarn.lock` contains changes, I have committed it
```

2019-02-26 13:17 UTC, yhuard approved these changes

2019-02-26 13:20 UTC, merged